### ISSUE TITLE
Update README to reflect that paranoia can be disabled and uninstalled with bee

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/paranoia#2]
The README currently states that the only way to disable `paranoia` is by updating in the `system` table.  This is not completely accurate.
Running: `bee dis paranoia` and `bee pmu paranoia` will disable and uninstall `paranoia` respectively.  If you're happy to include this, I'm happy to prepare a PR.

**Comment by laryn** [comment]
Sounds good -- thanks @yorkshire-pudding !
